In [1]:
import pandas as pd
import numpy as np

In [2]:
coordinateCsvFile = './India_Goa syst_2000_m.csv'
jsonFileName = coordinateCsvFile[:-3]+'json'

In [3]:
coordinateDf=pd.read_csv(coordinateCsvFile)
coordinateDf.head()

,id,latitude,longitude,OBJECTID,CE_ID,XCoordinate,YCoordinate,XCoordinat,YCoordinat,xCoordinate,yCoordinate,elevation,slope,aspect,climate,soil,gez,adm0_name,adm1_name,adm2_name
0,NaN,14.903051,74.084061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,1,180,10,7,11.0,India,Goa,South Goa
1,NaN,14.903051,74.102028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26,1,169,10,7,11.0,India,Goa,South Goa
2,NaN,14.921017,74.048129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89,1,240,0,0,0.0,India,Goa,South Goa
3,NaN,14.921017,74.066095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62,1,111,0,0,0.0,India,Goa,South Goa
4,NaN,14.921017,74.084061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53,1,165,10,7,11.0,India,Goa,South Goa

In [4]:
latLongArray=coordinateDf[['latitude','longitude','adm1_name','adm2_name']].values
print(latLongArray.shape)

(953, 4)

In [5]:
from collections import defaultdict
pointList = defaultdict(lambda: 'not_present')
for lat,long,adm1_name,adm2_name in latLongArray:
    pointList[(lat,long)]=(adm1_name,adm2_name)

In [6]:
latitudeUniqueValues=([t[0] for t in latLongArray])
myset = set(latitudeUniqueValues)
latitudeUniqueValues=list(myset)
latitudeUniqueValues.sort()
longitudeUniqueValues=([t[1] for t in latLongArray])
myset = set(longitudeUniqueValues)
longitudeUniqueValues=list(myset)
longitudeUniqueValues.sort()

In [7]:
temp=[]
for lat_index in range(len(latitudeUniqueValues)-1):
    for long_index in range(len(longitudeUniqueValues)-1):
        top_left_Point=(latitudeUniqueValues[lat_index],longitudeUniqueValues[long_index])
        top_rigt_Point=(latitudeUniqueValues[lat_index],longitudeUniqueValues[long_index+1])
        bot_left_Point=(latitudeUniqueValues[lat_index+1],longitudeUniqueValues[long_index])
        bot_rigt_Point=(latitudeUniqueValues[lat_index+1],longitudeUniqueValues[long_index+1])
        if(pointList[top_left_Point]!='not_present' and pointList[top_rigt_Point]!='not_present' and 
          pointList[bot_left_Point]!='not_present' and pointList[bot_rigt_Point]!='not_present'):
            temp.append(1)
        
        
print(len(temp))

832

In [10]:
initialStr='{"type": "FeatureCollection","features": ['
endStr=']}'


featureStr_List=[]
count_grid=0
for lat_index in range(len(latitudeUniqueValues)-1):
    for long_index in range(len(longitudeUniqueValues)-1):
        top_left_Point=(latitudeUniqueValues[lat_index],longitudeUniqueValues[long_index])
        top_rigt_Point=(latitudeUniqueValues[lat_index],longitudeUniqueValues[long_index+1])
        bot_left_Point=(latitudeUniqueValues[lat_index+1],longitudeUniqueValues[long_index])
        bot_rigt_Point=(latitudeUniqueValues[lat_index+1],longitudeUniqueValues[long_index+1])
        if(pointList[top_left_Point]!='not_present' and pointList[top_rigt_Point]!='not_present' and 
          pointList[bot_left_Point]!='not_present' and pointList[bot_rigt_Point]!='not_present'):
            featureStr = '{ "type": "Feature", "properties": { "ID": "'
            featureStr+= pointList[top_left_Point][0]+'@'+pointList[top_left_Point][1]+'@'+str(count_grid)
            count_grid+=1
            featureStr+='"}, "geometry": { "type": "Polygon", "coordinates": [ ['
            featureStr +='['+str(top_left_Point[1])+','+str(top_left_Point[0])+'],' 
            featureStr +='['+str(top_rigt_Point[1])+','+str(top_rigt_Point[0])+'],' 
            featureStr +='['+str(bot_rigt_Point[1])+','+str(bot_rigt_Point[0])+'],' 
            featureStr +='['+str(bot_left_Point[1])+','+str(bot_left_Point[0])+'],' 
            featureStr +='['+str(top_left_Point[1])+','+str(top_left_Point[0])+']' 
            featureStr+='] ] } }'
            featureStr_List.append(featureStr)
    

outputJson=initialStr+(','.join(featureStr_List))+endStr

In [11]:
f = open(jsonFileName, "w")
f.write(outputJson)
f.close()